name: AutoRestart
version: 1.8
## This is the version of the reimplementation of the reimplementation of TitleManager.
main: org.croniks.autorestart.core.Main
author: ServersMC, DennisLysenko
commands:
    autore:
        description: 'Main command for AutoRestart plugin!'
        usage: '/autore help'